"""
AgentState — shared state schema for the wealth management LangGraph pipeline.

Every node reads from and writes to this TypedDict as it flows through
the graph: fetch_crm → fetch_market → analyze_risk → generate_report → save_draft.
"""

from __future__ import annotations

from typing import TypedDict


class AgentState(TypedDict, total=False):
    """Shared state flowing through the supervisor graph.

    Fields
    ------
    client_id : str
        Salesforce Account / Contact identifier supplied at pipeline entry.
    portfolio_assets : list[dict]
        Client holdings retrieved from the CRM.
        Each dict: ``{"ticker": "AAPL", "quantity": 150, "asset_type": "equity"}``.
    market_data : dict
        Historical OHLCV data keyed by ticker, fetched from the OpenBB MCP
        server.  Structure: ``{"AAPL": [{"date": ..., "close": ...}, ...]}``.
    risk_metrics : dict
        Quantitative risk outputs computed by the TradingAgents skill.
        Keys include ``cvar_95``, ``cvar_99``, ``max_drawdown``,
        ``sharpe_ratio``, ``sortino_ratio``.
    final_report : str
        Structured Markdown wealth-management report generated by the
        FinRobot Director Agent.
    """

    client_id: str
    portfolio_assets: list[dict]
    market_data: dict
    risk_metrics: dict
    final_report: str
